name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  release-merge-images:
    name: Release Merge Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run SSI Crawling
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/cage1016/ak:0.1.0
          options: >
            --user root
            --env NUM_WORKERS=30
            -v ${{ github.workspace }}:/tmp/:rw
            -w /tmp
          run: /layers/google.go.build/bin/main alfred pack